* 6809 assembly program generated by cmoc 0.1.98


	SECTION	code


_cold_start	IMPORT
_dot	IMPORT
_dots	IMPORT
_init_os	IMPORT
_init_os_ram	IMPORT
_init_via	IMPORT
_intensity	IMPORT
_line	IMPORT
_lines	IMPORT
_move	IMPORT
_music_check	IMPORT
_music_get_flag	IMPORT
_music_play	IMPORT
_music_set_flag	IMPORT
_pattern_lines	IMPORT
_print_str	IMPORT
_print_str_c	IMPORT
_random	IMPORT
_random_seed	IMPORT
_read_buttons	IMPORT
_read_joystick	IMPORT
_reset_beam	IMPORT
_rotate	IMPORT
_set_refresh	IMPORT
_set_scale	IMPORT
_set_text_size	IMPORT
_wait_retrace	IMPORT
_warm_start	IMPORT


*******************************************************************************

* FUNCTION terminal_scroll(): defined at terminal.c:8
_terminal_scroll	EQU	*
.static.function.terminal_scroll	EQU	*
* Prototype: void terminal_scroll(void)
* Calling convention: 0 (CMOC Default)
	PSHS	U
	LEAU	,S
	LEAS	-2,S
* Local non-static variable(s):
*     -2,U:    2 bytes: i: int: line 10
* Line terminal.c:10: for init
* Line terminal.c:10: init of variable i
	CLRA
	CLRB
	STD	-2,U		variable i
	BRA	L00033		jump to for condition
L00032	EQU	*
* Line terminal.c:11: for body
* Line terminal.c:12: assignment: =
	LDD	-2,U		variable i
	ADDD	#$01		1
	LSLB
	ROLA
	LDX	#_terminalContent+0	address of array terminalContent (optim: removePCRIfRelocatabilityNotSupported)
* optim: optimizeLoadDX
	LDD	D,X		get r-value (optim: optimizeLoadDX)
	PSHS	B,A		right side of assignment
	LDD	-2,U		variable i
	LSLB
	ROLA
	LDX	#_terminalContent+0	address of array terminalContent (optim: removePCRIfRelocatabilityNotSupported)
	LEAX	D,X		add offset
	PULS	A,B		retrieve value to store
	STD	,X
* Useless label L00034 removed
* Line terminal.c:10: for increment(s)
	LDD	-2,U
	ADDD	#1
	STD	-2,U
L00033	EQU	*
* Line terminal.c:10: for condition
	LDD	-2,U		variable i
	CMPD	#$09
	BLT	L00032
* optim: branchToNextLocation
* Useless label L00035 removed
* Line terminal.c:15: assignment: =
	CLRA
	CLRB
* optim: stripUselessPushPull
* optim: optimizeLeax
* optim: stripUselessPushPull
	STD	_terminalContent+18	optim: optimizeLeax (optim: removePCRIfRelocatabilityNotSupported)
* Line terminal.c:16: assignment: =
	LDB	#$09		optim: removeAndOrMulAddSub
	STD	_currentLine+0	 (optim: removePCRIfRelocatabilityNotSupported)
* Useless label L00029 removed
	LEAS	,U
	PULS	U,PC
* END FUNCTION terminal_scroll(): defined at terminal.c:8
funcend_terminal_scroll	EQU *
funcsize_terminal_scroll	EQU	funcend_terminal_scroll-_terminal_scroll
_terminal_print	EXPORT


*******************************************************************************

* FUNCTION terminal_print(): defined at terminal.c:19
_terminal_print	EQU	*
* Prototype: void terminal_print(char *)
* Calling convention: 0 (CMOC Default)
	PSHS	U
	LEAU	,S
* Formal parameter(s):
*      4,U:    2 bytes: msg: char *: line 19
* Line terminal.c:21: if
	LDD	_currentLine+0	variable currentLine (optim: removePCRIfRelocatabilityNotSupported)
	CMPD	#$0A
	BLT	L00037		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00036 removed
* Line terminal.c:22
* Line terminal.c:23: function call: terminal_scroll()
	JSR	_terminal_scroll
L00037	EQU	*		else clause of if() started at terminal.c:21
* Useless label L00038 removed
* Line terminal.c:26: assignment: =
	LDD	4,U		variable `msg', declared at terminal.c:19
	PSHS	B,A		right side of assignment
	LDD	_currentLine+0	variable currentLine (optim: removePCRIfRelocatabilityNotSupported)
	LSLB
	ROLA
	LDX	#_terminalContent+0	address of array terminalContent (optim: removePCRIfRelocatabilityNotSupported)
	LEAX	D,X		add offset
	PULS	A,B		retrieve value to store
	STD	,X
* Line terminal.c:27: post-increment
	LDX	_currentLine+0	variable `currentLine', declared at terminal.c:27 (optim: removePCRIfRelocatabilityNotSupported)
	LEAX	1,X
	STX	_currentLine+0	 (optim: removePCRIfRelocatabilityNotSupported)
* Useless label L00030 removed
	LEAS	,U
	PULS	U,PC
* END FUNCTION terminal_print(): defined at terminal.c:19
funcend_terminal_print	EQU *
funcsize_terminal_print	EQU	funcend_terminal_print-_terminal_print
_terminal_render	EXPORT


*******************************************************************************

* FUNCTION terminal_render(): defined at terminal.c:30
_terminal_render	EQU	*
* Prototype: void terminal_render(void)
* Calling convention: 0 (CMOC Default)
	PSHS	U
	LEAU	,S
	LEAS	-2,S
* Local non-static variable(s):
*     -2,U:    2 bytes: i: int: line 32
* Line terminal.c:32: for init
* Line terminal.c:32: init of variable i
	CLRA
	CLRB
	STD	-2,U		variable i
	BRA	L00040		jump to for condition
L00039	EQU	*
* Line terminal.c:33: for body
* Line terminal.c:34: if
	LDD	-2,U		variable i
	LSLB
	ROLA
	LDX	#_terminalContent+0	address of array terminalContent (optim: removePCRIfRelocatabilityNotSupported)
* optim: optimizeLoadDX
	LDD	D,X		get r-value (optim: optimizeLoadDX)
* optim: loadCmpZeroBeqOrBne
	BEQ	L00044		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00043 removed
* Line terminal.c:35
* Line terminal.c:36: function call: reset_beam()
	JSR	_reset_beam
* Line terminal.c:37: function call: set_text_size()
	LDX	#$28		decimal 40 signed (optim: optimizeConsecutiveFunctionArguments)
* optim: optimizeConsecutiveFunctionArguments
	LDD	#$FFFA		constant expression: 65530 decimal, signed
	PSHS	X,B,A		C function argument 1 of set_text_size(): int (optim: optimizeConsecutiveFunctionArguments)
	JSR	_set_text_size
	LEAS	4,S
* Line terminal.c:38: function call: print_str_c()
	LDD	-2,U		variable i
	LSLB
	ROLA
	LDX	#_terminalContent+0	address of array terminalContent (optim: removePCRIfRelocatabilityNotSupported)
	LEAX	D,X		add offset
	LDD	,X		get r-value
	PSHS	B,A		C function argument 3 of print_str_c(): char *
	LDB	#$88		optim: lddToLDB
* Cast from `int' to byte: result already in B
	SEX			promoting byte argument to word
	PSHS	B,A		C function argument 2 of print_str_c(): char
	LDD	-2,U		variable `i', declared at terminal.c:32
	LBSR	MUL16BY10
	PSHS	B,A		operands of subtraction are not both byte-sized
	CLRA
	CLRB
	SUBD	,S++
* Cast from `int' to byte: result already in B
	SEX			promoting byte argument to word
	PSHS	B,A		C function argument 1 of print_str_c(): char
	JSR	_print_str_c
	LEAS	6,S
L00044	EQU	*		else clause of if() started at terminal.c:34
* Useless label L00045 removed
* Useless label L00041 removed
* Line terminal.c:32: for increment(s)
	LDD	-2,U
	ADDD	#1
	STD	-2,U
L00040	EQU	*
* Line terminal.c:32: for condition
	LDD	-2,U		variable i
	CMPD	_currentLine+0,PCR	variable currentLine
	BGE	L00042		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00046 removed
	LDD	-2,U		variable i
	CMPD	#$0A
	LBLT	L00039
* optim: branchToNextLocation
L00042	EQU	*		end for
* Useless label L00031 removed
	LEAS	,U
	PULS	U,PC
* END FUNCTION terminal_render(): defined at terminal.c:30
funcend_terminal_render	EQU *
funcsize_terminal_render	EQU	funcend_terminal_render-_terminal_render


	ENDSECTION




	SECTION	initgl




*******************************************************************************

* Initialize global variables.


	ENDSECTION




	SECTION	rodata


string_literals_start	EQU	*
string_literals_end	EQU	*


*******************************************************************************

* READ-ONLY GLOBAL VARIABLES


	ENDSECTION




*******************************************************************************

* WRITABLE DATA SECTION


	SECTION	rwdata


* Statically-initialized global variables
_currentLine	EQU	*		currentLine: int: terminal.c:6
	FDB	$00		decimal 0
.global.static.variable.currentLine	EQU	*
* Statically-initialized local static variables


	ENDSECTION




	SECTION	bss


bss_start	EQU	*
* Uninitialized global variables
_terminalContent	EQU	*
	RMB	20		terminalContent: char *[]: terminal.c:5
.global.static.variable.terminalContent	EQU	*
* Uninitialized local static variables
bss_end	EQU	*


	ENDSECTION




*******************************************************************************

* Importing 4 utility routine(s).
MUL16BY10	IMPORT
_print_str_c	IMPORT
_reset_beam	IMPORT
_set_text_size	IMPORT


*******************************************************************************

	END
